
spring:
  datasource:
    #    url: jdbc:postgresql://127.0.0.1:5332/fullstack
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/bank/protocol/openid-connect/certs

